theme = "base16_transparent"

[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
C-y = [
  ':sh rm -f /tmp/files2open',
  ':set mouse false',
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/files2open',
  ':redraw',
  ':set mouse true',
  ':open /tmp/files2open',
  'select_all',
  'split_selection_on_newline',
  'goto_file',
  ':buffer-close! /tmp/files2open',
]

[keys.normal."space"]
j = { k = ":w!", q = ":q!" }
l = { g = ":sh lazygit"}
